# general
phase_name: "adecorte"
# ocp setup
cluster_name: "adecorte"
azure_dns_zone: "demo.az.red-chesterfield.com"
# AAP setup
controller_host: "https://controller.dev.mgmt.ansiblecloud.com"
vault_uri: "https://kv-acmsre-team.vault.azure.net"
