---
# This is the reference playbook that is used to develop the flow.
# Another version of this playbook is also avaiable in the AOC project.

- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    # The following line is necessary because the generated inventory file
    # has this set to true.  We don't need to use sudo for the following
    # operations.
    ansible_become: false
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    acm_localhost_inventory: "ACM localhost"

  tasks:
    - name: Include secret propagator roles
      ansible.builtin.include_role:
        name: ../roles/aap_controller_acm_workflow_secret_sync
        tasks_from: main
